version: '3.0'
services:
  database:
    image: 'mariadb:10.3'
    container_name: database
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - "database_volume:/var/lib/mysql/"
  frontend:
    image: 'node:alpine3.16'
    container_name: frontend
    restart: always
    tty: true
    volumes:
      - type: bind
        source: ./srcs/frontend
        target: /app
    ports:
      - 80:80
  backend:
    image: 'python:3.9'
    container_name: backend
    tty: true
    restart: always
    volumes:
      - type: bind
        source: ./srcs/backend
        target: /app
    ports:
      - 3000:3000

volumes:
    database_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: "/Users/${USER}/hackathon/data/mariadb"
